### ISSUE TITLE
Merging the branch 0.9.0 back into Master

### ISSUE THREAD

**Issue by smallfly** [kylemcdonald/ofxBlackmagic#11]
Hi @kylemcdonald ,

Could we merge the 0.9.0 branch into Master?

Thanks

**Comment by DEM0915** [comment]
try this one:[ofxDeckLink](https://github.com/hanasaan/ofxDeckLink)

**Comment by kylemcdonald** [comment]
I've merged it. But my guess is that the ofxDeckLink by @hanasaan and @satoruhiga is better :)
